[project]
name = "clustermap-imshow"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.14"
dependencies = [
    "scipy>=1.17.0",
    "seaborn>=0.13.2",
]

[dependency-groups]
dev = [
    "fastcluster>=1.3.0",
]
